on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Install
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Vendor # FIXME: remove this step when migrating to pure Go modules.
      run: go mod vendor

    - name: Build
      run: make build

    - name: Test
      run: make test
